# Site settings
title: Miguel Augusto
email: teratomaquia@gmail.com
url: https://elysianspace.github.io/
description: "Autor. Literato. Lobisomem."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Teratomaquia

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: pen
    url: https://teratomaquia.dreamwidth.org
  - title: twitter
    url: https://twitter.com/teratomaquia
  - title: medium
    url: http://medium.com/@teratomaquia
  - title: ello
    url: http://ello.co/teratomaquia
  - title: pen-nib
    url: http://wattpad.com/teratomaquia

# Build settings
markdown: kramdown
permalink: pretty
